# Use a Python base image
FROM python:3.12.1-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the worker script into the container
COPY . .

# Set the default command to run the worker script
CMD ["python", "worker.py"]
